[instance]
problem_instance = "/fjsp_sdst/1_Fattahi/Fattahi_setup_07.fjs" # configure problem instance to be scheduled

[solver]
time_limit = 3600 # time limit for the OR-tools CP-SAT solver, in seconds

[output]
plotting = true # draw ganttchart of found solution